apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.name" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "backend.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}

    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"

            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.SPRING_DATASOURCE_URL }}"
            - name: REDIS_HOST
              value: "{{ .Values.env.REDIS_HOST }}"
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}
            - name: MARKET_PUBSUB_CHANNEL
              value: "{{ .Values.env.MARKET_PUBSUB_CHANNEL }}"
            - name: STELLAR_JWT_ENABLED
              value: "{{ .Values.env.STELLAR_JWT_ENABLED }}"
            - name: STELLAR_JWT_ISSUER
              value: "{{ .Values.env.STELLAR_JWT_ISSUER }}"
            - name: STELLAR_JWT_AUDIENCE
              value: "{{ .Values.env.STELLAR_JWT_AUDIENCE }}"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SPRING_DATASOURCE_PASSWORD
            - name: STELLAR_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: STELLAR_JWT_SECRET

          resources:
{{ toYaml .Values.resources | indent 12 }}
